# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: Unity_Variable_Group


trigger: none
resources:
  pipelines:
    - pipeline: MyTriggerPipeline
      # project: Pipelining
      source: 04-Unity BusinessLines PAProxy (CD)
      trigger: 
        branches:
          include:
          - master

pool: Default

steps:
# start of update packages
  - checkout: self 
    displayName: Checkout $(Build.Repository.Name)
    persistCredentials: true 
    clean: true 


  - task: CmdLine@2 
    displayName: pull $(Build.Repository.Name)
    inputs: 
      script: | 
        git  pull origin HEAD:master 

  - task: DotNetCoreCLI@2
    displayName: 'clear local cache'
    inputs:
      command: custom
      custom: nuget
      arguments: 'locals http-cache --clear'

  - task: DotNetCoreCLI@2
    displayName: 'Update BaseDomain Package'
    inputs:
      command: custom
      projects: '**/MazaNetCOreFw.TicketingDomain.csproj'
      custom: add
      arguments: 'package MazaNetCOreFw.BaseDomain --source http://172.22.0.44:8008/v3/index.json --version $(Unity_BuildNumber)'

  - task: DotNetCoreCLI@2
    displayName: 'Update SharedPersistence Package'
    inputs:
      command: custom
      projects: '**/MazaNetCOreFw.TicketingPersistence.csproj'
      custom: add
      arguments: 'package MazaNetCOreFw.SharedPersistence --source http://172.22.0.44:8008/v3/index.json --version $(Unity_BuildNumber)'

  - task: DotNetCoreCLI@2
    displayName: 'Update SharedService Package'
    inputs:
      command: custom
      projects: '**/MazaNetCOreFw.TicketingService.csproj'
      custom: add
      arguments: 'package MazaNetCOreFw.SharedService --source http://172.22.0.44:8008/v3/index.json --version $(Unity_BuildNumber)'


  - task: CmdLine@2 
    displayName: add files to $(Build.Repository.Name)
    inputs: 
      script: | 
        git add --all 

  - task: CmdLine@2 
    displayName: commit $(Build.Repository.Name)
    continueOnError: true
    inputs: 
      script: | 
        git commit -m "Pipeline: Automatic Repository Integration" 

  - task: CmdLine@2 
    displayName: push $(Build.Repository.Name)
    inputs: 
      script: | 
        git  push -u origin HEAD:master --force

# end of update packages
  - task: DotNetCoreCLI@2
    displayName: "build Domain"
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: $(Unity_BuildConfiguration)



  - task: DotNetCoreCLI@2
    displayName: "pack domain"
    inputs:
      command: 'pack'
      packagesToPack: '**/MazaNetCOreFw.TicketingDomain.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Unity_BuildNumber

  - task: DotNetCoreCLI@2
    displayName: "pack Persistence"
    inputs:
      command: 'pack'
      packagesToPack: '**/MazaNetCOreFw.TicketingPersistence.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Unity_BuildNumber

  - task: DotNetCoreCLI@2
    displayName: "pack Service"
    inputs:
      command: 'pack'
      packagesToPack: '**/MazaNetCOreFw.TicketingService.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Unity_BuildNumber

  - task: DotNetCoreCLI@2
    displayName: "pack Infrastructure"
    inputs:
      command: 'pack'
      packagesToPack: '**/MazaNetCOreFw.TicketingInfrastructure.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Unity_BuildNumber
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'eb1228b2-0814-44b8-9ccc-817f27ef02bb/b2622bcc-02ff-494e-aca4-8f2ae212b571'

  - task: NuGetCommand@2
    displayName: 'NuGet Push to BaGet'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: MyBaGetServiceConnection

